[2022-12-04T06:23:48.484+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cp_webcheck_failed.http_check scheduled__2022-12-03T00:00:00+00:00 [queued]>
[2022-12-04T06:23:48.523+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cp_webcheck_failed.http_check scheduled__2022-12-03T00:00:00+00:00 [queued]>
[2022-12-04T06:23:48.529+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-04T06:23:48.530+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-04T06:23:48.532+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-04T06:23:48.587+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): http_check> on 2022-12-03 00:00:00+00:00
[2022-12-04T06:23:48.643+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cp_webcheck_failed', 'http_check', 'scheduled__2022-12-03T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/cp_webcheck_failed.py', '--cfg-path', '/tmp/tmpuro02xk4']
[2022-12-04T06:23:48.647+0000] {standard_task_runner.py:83} INFO - Job 129: Subtask http_check
[2022-12-04T06:23:48.605+0000] {standard_task_runner.py:55} INFO - Started process 62 to run task
[2022-12-04T06:23:48.908+0000] {task_command.py:376} INFO - Running <TaskInstance: cp_webcheck_failed.http_check scheduled__2022-12-03T00:00:00+00:00 [running]> on host 71a129efd3d8
[2022-12-04T06:23:49.171+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cp_webcheck_failed
AIRFLOW_CTX_TASK_ID=http_check
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-03T00:00:00+00:00
[2022-12-04T06:23:49.176+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-04T06:23:49.193+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -s https://localhost > /dev/null']
[2022-12-04T06:23:49.229+0000] {subprocess.py:86} INFO - Output:
[2022-12-04T06:23:49.302+0000] {subprocess.py:97} INFO - Command exited with return code 7
[2022-12-04T06:23:49.314+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2022-12-04T06:23:49.319+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=cp_webcheck_failed, task_id=http_check, execution_date=20221203T000000, start_date=20221204T062348, end_date=20221204T062349
[2022-12-04T06:23:49.365+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 129 for task http_check (Bash command failed. The command returned a non-zero exit code 7.; 62)
[2022-12-04T06:23:49.414+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-04T06:23:49.526+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
