[2022-11-29T00:38:11.471+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cp_webcheck_failed_copy.http_check_copy scheduled__2022-11-28T00:00:00+00:00 [queued]>
[2022-11-29T00:38:11.485+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cp_webcheck_failed_copy.http_check_copy scheduled__2022-11-28T00:00:00+00:00 [queued]>
[2022-11-29T00:38:11.487+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T00:38:11.488+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-29T00:38:11.491+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T00:38:11.512+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): http_check_copy> on 2022-11-28 00:00:00+00:00
[2022-11-29T00:38:11.524+0000] {standard_task_runner.py:55} INFO - Started process 73264 to run task
[2022-11-29T00:38:11.539+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cp_webcheck_failed_copy', 'http_check_copy', 'scheduled__2022-11-28T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/cp_webcheck_failed copy.py', '--cfg-path', '/tmp/tmpi1jafc63']
[2022-11-29T00:38:11.599+0000] {standard_task_runner.py:83} INFO - Job 106: Subtask http_check_copy
[2022-11-29T00:38:11.704+0000] {task_command.py:376} INFO - Running <TaskInstance: cp_webcheck_failed_copy.http_check_copy scheduled__2022-11-28T00:00:00+00:00 [running]> on host 71a129efd3d8
[2022-11-29T00:38:11.797+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cp_webcheck_failed_copy
AIRFLOW_CTX_TASK_ID=http_check_copy
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T00:00:00+00:00
[2022-11-29T00:38:11.800+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T00:38:11.803+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -s https://localhost > /dev/null']
[2022-11-29T00:38:11.845+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T00:38:11.858+0000] {subprocess.py:97} INFO - Command exited with return code 7
[2022-11-29T00:38:11.872+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2022-11-29T00:38:11.892+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=cp_webcheck_failed_copy, task_id=http_check_copy, execution_date=20221128T000000, start_date=20221129T003811, end_date=20221129T003811
[2022-11-29T00:38:11.905+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 106 for task http_check_copy (Bash command failed. The command returned a non-zero exit code 7.; 73264)
[2022-11-29T00:38:13.182+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T00:38:13.440+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
